### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet.js#2]
Javascript is fun and mxnet.js enables arbitrary graph executions, making it ideal for building interactive examples. This is a roadmap on adding support of features, as well as brainstorming what can be added. Contribution is more than welcomed!
## Code and Demo Structure
- [ ] Refactor code to move things into demo subfolder, need to deal with emscripten
- [ ] Build specific libraries for specific tasks, see Application 
## Applications
- [x] Image classification
- [ ] Image segmentation
- [ ]  Text generation with RNN
- [ ] Image captioning
